function updateCar2D(position, currentSpeed, desiredSpeed, throttle, brake)
% position     : m
% currentSpeed : km/h
% desiredSpeed : km/h
% throttle     : 0 hoặc 1
% brake        : 0 hoặc 1

persistent fig ax car roadTop roadBottom centerLine infoText statusText

% Tạo lại cửa sổ nếu chưa tồn tại hoặc đã bị đóng
if isempty(fig) || ~isgraphics(fig)

    fig = figure( ...
        'Name', 'ACC 2D Vehicle Simulation', ...
        'NumberTitle', 'off', ...
        'Color', [0.85 0.92 1.00]);

    ax = axes(fig);
    hold(ax, 'on');

    % Hai biên của đường
    roadTop = plot(ax, [0 100], [3 3], ...
        'Color', 'white', 'LineWidth', 3);

    roadBottom = plot(ax, [0 100], [-1 -1], ...
        'Color', 'white', 'LineWidth', 3);

    % Vạch giữa đường
    centerLine = plot(ax, [0 100], [1 1], '--', ...
        'Color', [1 1 0], 'LineWidth', 1.5);

    % Hình chiếc xe
    car = rectangle(ax, ...
        'Position', [position 0 8 2], ...
        'Curvature', 0.2, ...
        'FaceColor', [0 0.65 0], ...
        'EdgeColor', 'black', ...
        'LineWidth', 1.5);

    % Thông tin tốc độ
    infoText = text(ax, position, 6, '', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'Color', 'black');

    % Trạng thái xe
    statusText = text(ax, position, 4.8, '', ...
        'FontSize', 12, ...
        'FontWeight', 'bold');

    xlabel(ax, 'Distance (m)');
    ylabel(ax, 'Road');
    title(ax, 'Adaptive Cruise Control - 2D Simulation');

    grid(ax, 'on');

    ax.Color = [0.25 0.25 0.25];
    ax.YLim = [-2 8];
end

% Chọn màu và trạng thái của xe
if brake > 0.5
    carColor = [0.90 0.10 0.10];
    vehicleStatus = 'BRAKING';
    statusColor = [0.90 0.10 0.10];

elseif throttle > 0.5
    carColor = [0.10 0.75 0.20];
    vehicleStatus = 'ACCELERATING';
    statusColor = [0.00 0.55 0.10];

else
    carColor = [0.10 0.45 0.95];
    vehicleStatus = 'HOLDING SPEED';
    statusColor = [0.10 0.30 0.90];
end

% Di chuyển xe
set(car, ...
    'Position', [position 0 8 2], ...
    'FaceColor', carColor);

% Camera đi theo xe
leftLimit = max(0, position - 20);
rightLimit = leftLimit + 100;

ax.XLim = [leftLimit rightLimit];

% Cập nhật đường theo camera
set(roadTop, ...
    'XData', [leftLimit rightLimit], ...
    'YData', [3 3]);

set(roadBottom, ...
    'XData', [leftLimit rightLimit], ...
    'YData', [-1 -1]);

set(centerLine, ...
    'XData', [leftLimit rightLimit], ...
    'YData', [1 1]);

% Cập nhật thông tin
information = sprintf([ ...
    'Distance: %.1f m\n' ...
    'Current Speed: %.1f km/h\n' ...
    'Desired Speed: %.1f km/h\n' ...
    'Throttle: %.0f %%\n' ...
    'Brake: %.0f %%'], ...
    position, ...
    currentSpeed, ...
    desiredSpeed, ...
    throttle * 100, ...
    brake * 100);

set(infoText, ...
    'Position', [leftLimit + 3, 6, 0], ...
    'String', information);

set(statusText, ...
    'Position', [leftLimit + 65, 6, 0], ...
    'String', vehicleStatus, ...
    'Color', statusColor);

drawnow limitrate;
end